module.exports = {
    tags: {
        allowUnknownTags: true,
        dictionaries: ['jsdoc'],
    },
    tagNamePreference: {
        definedTags: ["regleMetier"],
    },
    plugins: ['plugins/markdown'],
    templates: {
        logoFile: '',
        cleverLinks: false,
        monospaceLinks: true,
        dateFormat: 'ddd MMM Do YYYY',
        outputSourceFiles: true,
        outputSourcePath: true,
        systemName: 'Concerts Service API',
        footer: '',
        copyright: 'Aissous-Amin',
        navType: 'vertical',
        theme: 'flatly',
        linenums: true,
        collapseSymbols: false,
        inverseNav: true,
        highlightTutorialCode: true,
        protocol: 'html://',
        methodHeadingReturns: true,
        encoding: 'utf8',
        private: true,
        recurse: true,
        sortByName: true,
        stripModuleName: 'concerts-service',
    },
    markdown: {
        parser: 'gfm',
        hardwrap: true,
    },
    source: {
        include: [
            'README.md',
            'Config',
            'Source/controllers',
            'Source/models',
            'Source/routes',
            'Source/services',
            'Source/utils',
        ],
        excludePattern: 'node_modules',
        includePattern: '.+\\.js(doc|x)?$',
    },
    opts: {
        template: 'node_modules/better-docs',
        destination: './Docs/jsdoc',
    },
};
